### PR TITLE
Provide option to randomise id

### PR DESCRIPTION
**Pull request by sl4m**
This will help find bugs.

### CODE REVIEW

**Comment by mylesmegyesi** [comment]
Please fix the misspelling in your commit message.

On Sunday, February 15, 2015, skim <notifications@github.com> wrote:

> This will help find bugs.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/mylesmegyesi/memorydb/pull/3
> Commit Summary
>
>    - provide option to randomise id
>
> File Changes
>
>    - *M* lib/memorydb/db.rb
>    <https://github.com/mylesmegyesi/memorydb/pull/3/files#diff-0> (12)
>    - *M* memorydb.gemspec
>    <https://github.com/mylesmegyesi/memorydb/pull/3/files#diff-1> (6)
>    - *M* spec/repository_examples.rb
>    <https://github.com/mylesmegyesi/memorydb/pull/3/files#diff-2> (15)
>
> Patch Links:
>
>    - https://github.com/mylesmegyesi/memorydb/pull/3.patch
>    - https://github.com/mylesmegyesi/memorydb/pull/3.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mylesmegyesi/memorydb/pull/3>.
>


-- 
Myles

**Comment by sl4m** [comment]
:information_desk_person: Done.

**Comment by sl4m** [comment]
Any chance you can publish the new version?

**Comment by mylesmegyesi** [comment]
Done.

**Pull request merged**
